### ISSUE TITLE
how to automatically deal circularization problem in **trycycler reconcile** step

### ISSUE THREAD

**Issue by yipukangda** [rrwick/Trycycler#39] opened 2022-06-16 02:19 UTC
Hi, 
After assembly and cluster step, durning _**reconcile**_ process I meet a error as:
```
Error: failed to circularise sequence K_utg000001l because its end could not be found in other
sequences. You can either trim some sequence off the end of K_utg000001l or exclude the sequence
altogether and try again.
```
Then the whole workflow stacked,  how to continue with this process by some automatic operations.

Thanks

**Comment by propan2one** [comment] 2022-09-08 08:10
Hi I made tests to put back the clusterized sequences with the same start using `circlator fixstart` from [circlator](https://github.com/sanger-pathogens/circlator) before to `trycycler reconcile` and I managed to overcome this step. Maybe it will help you, if so don't hesitate to send a feedback.

**Comment by rrwick** [comment] 2023-03-15 01:56
There is currently no way to fully automate Trycycler's reconciliation process, and that's partly by design. Having a human think about the result and making a decision is key to Trycycler producing solid results. This is partly because a person can problem-solve tough cases better than a program. And partly because I want the user to abort the process if there are too many issues - e.g. if reconciliation is hard, that's a red flag that the dataset might be dodgy.

However, it is definitely true that Trycycler reconcile could be more efficient. Instead of stopping after each bad contig, it could assess all contigs and then stop. This would allow users to complete the process with fewer attempts, and this is something I'd like to address in the future. I'll close this issue now, but I'm leaving #47 (similar issue) open as an enhancement request.

Thanks!
Ryan

**Closed by rrwick** 2023-03-15 01:56 UTC
